"""创建聊天记录表

Revision ID: 0b4cd659f333
Revises: 88710f4e8ef4
Create Date: 2020-05-19 15:10:24.454712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b4cd659f333'
down_revision = '88710f4e8ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=True, comment='接收方'),
    sa.Column('sender_id', sa.Integer(), nullable=True, comment='发送方'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('message', sa.String(length=128), nullable=True, comment='消息'),
    sa.Column('type', sa.String(length=8), nullable=True, comment='消息类型'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_log')
    # ### end Alembic commands ###
